image: node:latest

stages:
  - pre-build
  - build
  - code-quality
  - containerize
  - deploy

install-dependencies-job:
  stage: pre-build
  script:
    - npm install -g yarn
    - yarn install --frozen-lockfile

build-job:
  stage: build
  script:
    - yarn build

storybook-build-job:
  stage: build
  script:
    - yarn storybook:build

lint-test-job:
  stage: code-quality
  script:
    - yarn lint

unit-test-job:
  stage: code-quality
  script:
    - yarn test

containerize-storybook:
  stage: containerize
  script:
    - echo "containerize storybook"

containerize-coverage:
  stage: containerize
  script:
    - echo "containerize code coverage"

package-publish-job:
  stage: deploy
  script:
    - echo "package deploy job..."

uxpin-publish-job:
  stage: deploy
  script:
    - echo "uxpin deploy job..."

