name: Storybook Docker Deploy

on:
  release:
    types: [created]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: 398149845386.dkr.ecr.us-east-1.amazonaws.com/nightowl-developers-registry
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-storybook


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Extract repository metadata
      id: extract_repository_metadata
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        
    - name: Setup node environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Install dependencies
      run: yarn install --frozen-lock

    - name: Build storybook
      run: yarn storybook:build
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: styless-storybook
        SOURCE_BRANCH: ${{ steps.extract_repository_metadata.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.extract_repository_metadata.outputs.SOURCE_TAG }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY-$SOURCE_BRANCH:$SOURCE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY-$SOURCE_BRANCH:$SOURCE_TAG
